export * from "./checkout"
export * from "./contact"

export { default as Home } from "./home"
export { default as CheckoutPage } from "./checkout"
export { default as ContactPage } from "./contact"
export { default as ProductDetailPage } from "./product-detail"
export { default as ImpressumPage } from "./impressum"
export { default as TermsAndConditionsPage } from "./terms-and-conditions"
export { default as PrivacyPolicyPage } from "./privacy-policy"
export { default as ReturnPolicyPage } from "./return-policy"
