export const defaultValues = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  deliveryStreetName: "",
  deliveryHouseNumber: "",
  deliveryZip: "",
  deliveryCity: "",
  deliveryCountry: "",
  companyName: "",
  companyRegistrationNumber: "",
  taxIdentificationNumber: "",
  vatNumber: "",
  invoiceStreetName: "",
  invoiceHouseNumber: "",
  invoiceZip: "",
  invoiceCity: "",
  invoiceCountry: "",
  isCompany: false,
  isDifferentInvoice: false,
  orderNotes: "",
  hasCheckedTerms: false,
};
